name: Hugo Actions  

on:
  push:
    branches:
      - main  

jobs:
  deploy: 
    runs-on: ubuntu-20.04	       
    steps:
      - uses: actions/checkout@v4       
        with:
         submodules: recursive        
         fetch-depth: 0                
         
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "3292722614@qq.com"
          git config user.name "worhllo"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push

      - name: Setup Hugo	       
        uses: peaceiris/actions-hugo@v2	
        with:
          hugo-version: 'latest'	

      - name: Build 
        run: hugo -D	
       

      - name: Deploy To WebStack-dev                       
        uses: peaceiris/actions-gh-pages@v3             
        with:
          external_repository: worhllo/WebStack-dev 	
      
          personal_token: ${{ secrets. }}	  
          
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          cname: 
          full_commit_message: ${{ github.event.head_commit.message }}